version: '3.9'

services:
  mongo:
    image: mongo:
    container_name: mongo-server
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - '27017:27017'