spring:
  application:
    name: product-service
  data:
    mongodb:
      database: productdb
      username: user
      password: password
      host: localhost
      port: 27017
      authentication-database: admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
server:
  port: 9020